# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titles',
        ),
    ]
