# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170704_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='titles',
            new_name='title',
        ),
    ]
